### Importing data set

In [7]:
import pandas as pd

url='https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day35-complete-case-analysis/data_science_job.csv'

df=pd.read_csv(url)

df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  18679 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  float64
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  training_hours          18392 non-null  float64
 12  target                  19158 non-null  float64
dtypes: float64(4), int64(1), object(8)
memory usage: 1.9+ MB

In [10]:
df.isnull().mean()

enrollee_id               0.000000
city                      0.000000
city_development_index    0.025003
gender                    0.235306
relevent_experience       0.000000
enrolled_university       0.020148
education_level           0.024011
major_discipline          0.146832
experience                0.003393
company_size              0.309949
company_type              0.320493
training_hours            0.039983
target                    0.000000
dtype: float64

### Train Test Split

In [14]:
from sklearn.model_selection import train_test_split

X=df.drop(columns=['target'], axis=1)
Y=df['target']

X_train, X_test, Y_train, Y_test =train_test_split(X, Y, test_size=0.2, random_state=42)

### Column Transformer by using Simple Imputer but with different strategies

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

trf=ColumnTransformer([
    ('impute_training_hours', SimpleImputer(strategy='mean'), ['training_hours']),
    ('impute_city_development_index', SimpleImputer(strategy='median'), ['city_development_index']),
    ('impute_experience', SimpleImputer(strategy='median'), ['experience']),
    ('impute_enrolled_university', SimpleImputer(strategy='most_frequent'), ['enrolled_university']),
    ('impute_education_level', SimpleImputer(strategy='most_frequent'), ['education_level']),
    ('impute_gender', SimpleImputer(strategy='constant', fill_value='Missing'), ['gender']),  
    ('impute_major_discipline', SimpleImputer(strategy='constant', fill_value='Missing'), ['major_discipline']),
    ('impute_company_size', SimpleImputer(strategy='constant' , fill_value='Missing'), ['company_size']),
    ('impute_company_type', SimpleImputer(strategy='constant' , fill_value='Missing'), ['company_type']),
], remainder='passthrough')

### Pipeline

In [22]:
from sklearn.pipeline import Pipeline

pipe=Pipeline([
    ('pre_processing', trf)
])

X_train_transformed=pipe.fit_transform(X_train)
X_test_Transformed=pipe.transform(X_test)

### Converting back into Data Frame

In [27]:
import numpy as np

cols=['training_hours', 'city_development_index', 'experience', 'enrolled_university', 'education_level', 'gender', 'major_discipline' , 'company_size', 'company_type'] + [c for c in X_train.columns if c not in ['training_hours', 'city_development_index', 'experience', 'enrolled_university', 'education_level', 'gender', 'major_discipline' ,'company_size', 'company_type']]

final_data_set=pd.DataFrame(X_train_transformed, columns=cols)

final_data_set.head()

,training_hours,city_development_index,experience,enrolled_university,education_level,gender,major_discipline,company_size,company_type,enrollee_id,city,relevent_experience
0,16.0,0.91,2.0,no_enrollment,High School,Missing,Missing,Missing,Missing,13163,city_16,No relevent experience
1,262.0,0.897,6.0,no_enrollment,Masters,Male,STEM,1000-4999,Pvt Ltd,9357,city_136,Has relevent experience
2,24.0,0.91,3.0,no_enrollment,Graduate,Male,Missing,Missing,Missing,604,city_16,No relevent experience
3,35.0,0.91,3.0,no_enrollment,High School,Male,Missing,Missing,Missing,19033,city_16,No relevent experience
4,43.0,0.903,4.0,Full time course,Graduate,Male,STEM,Missing,Missing,4825,city_145,Has relevent experience

In [28]:
final_data_set.isnull().mean()

training_hours            0.0
city_development_index    0.0
experience                0.0
enrolled_university       0.0
education_level           0.0
gender                    0.0
major_discipline          0.0
company_size              0.0
company_type              0.0
enrollee_id               0.0
city                      0.0
relevent_experience       0.0
dtype: float64