### Importing Data Set

In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv('train.csv')

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Feature Construction

In [2]:
df['family_size']=df['SibSp']+df['Parch']+1

print(df['family_size'])

0      2
1      2
2      1
3      2
4      1
      ..
886    1
887    1
888    4
889    1
890    1
Name: family_size, Length: 891, dtype: int64

### Feature Splitting

In [3]:
df['title']= df['Name'].str.split(',').str.get(1).str.split('.').str.get(0).str.strip()

print(df['title'])

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: title, Length: 891, dtype: object

### Dropping Extra Columns

In [5]:
df.drop(columns=['SibSp', 'Parch','Name'], inplace=True)

### Final Data Set

In [6]:
df.head()

,PassengerId,Survived,Pclass,Sex,Age,Ticket,Fare,Cabin,Embarked,family_size,title
0,1,0,3,male,22.0,A/5 21171,7.2500,NaN,S,2,Mr
1,2,1,1,female,38.0,PC 17599,71.2833,C85,C,2,Mrs
2,3,1,3,female,26.0,STON/O2. 3101282,7.9250,NaN,S,1,Miss
3,4,1,1,female,35.0,113803,53.1000,C123,S,2,Mrs
4,5,0,3,male,35.0,373450,8.0500,NaN,S,1,Mr