### Importing Data Set

In [1]:
import pandas as pd

url='https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day35-complete-case-analysis/data_science_job.csv'

df=pd.read_csv(url)

df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  18679 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  float64
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  training_hours          18392 non-null  float64
 12  target                  19158 non-null  float64
dtypes: float64(4), int64(1), object(8)
memory usage: 1.9+ MB

In [2]:
df.isnull().mean()

enrollee_id               0.000000
city                      0.000000
city_development_index    0.025003
gender                    0.235306
relevent_experience       0.000000
enrolled_university       0.020148
education_level           0.024011
major_discipline          0.146832
experience                0.003393
company_size              0.309949
company_type              0.320493
training_hours            0.039983
target                    0.000000
dtype: float64

In [4]:
df['experience'].unique()

array([20., 15.,  5.,  0., 11., 13.,  7., 17.,  2., 16.,  1.,  4., 10.,
       14., 18., 19., 12.,  3.,  6.,  9.,  8., nan])

### Train Test Split

In [7]:
from sklearn.model_selection import train_test_split

X=df.drop(columns=['target'], axis=1)
Y=df['target']

X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2, random_state=42)

### Colum Transformer By using Simple Imputer

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

trf=ColumnTransformer([
    ('imputer_city', SimpleImputer(strategy='mean'), ['city_development_index']),
    ('impute_hours', SimpleImputer(strategy='median'), ['training_hours']),
    ('impute_exp', SimpleImputer(strategy='constant', fill_value=99), ['experience'])
], remainder='passthrough')

### Pipeline

In [12]:
import numpy as np
from sklearn.pipeline import Pipeline

pipe=Pipeline([
    ('pre_processing', trf)
])

X_train_transformed=pipe.fit_transform(X_train)
X_test_transformed=pipe.transform(X_test)

### Converting into DataFrame

In [13]:
cols=['city_development_index', 'training_hours', 'experience'] + [c for c in X_train.columns if c not in ['city_development_index', 'training_hours', 'experience']]
df_final=pd.DataFrame(X_train_transformed, columns=cols)

df_final.head()

,city_development_index,training_hours,experience,enrollee_id,city,gender,relevent_experience,enrolled_university,education_level,major_discipline,company_size,company_type
0,0.91,16.0,2.0,13163,city_16,NaN,No relevent experience,no_enrollment,High School,NaN,NaN,NaN
1,0.897,262.0,6.0,9357,city_136,Male,Has relevent experience,no_enrollment,Masters,STEM,1000-4999,Pvt Ltd
2,0.91,24.0,3.0,604,city_16,Male,No relevent experience,NaN,NaN,NaN,NaN,NaN
3,0.91,35.0,3.0,19033,city_16,Male,No relevent experience,no_enrollment,High School,NaN,NaN,NaN
4,0.829253,43.0,4.0,4825,city_145,Male,Has relevent experience,Full time course,Graduate,STEM,NaN,NaN

In [14]:
df_final.isnull().sum()

city_development_index       0
training_hours               0
experience                   0
enrollee_id                  0
city                         0
gender                    3639
relevent_experience          0
enrolled_university        311
education_level            370
major_discipline          2237
company_size              4779
company_type              4943
dtype: int64

In [15]:
df_final.isnull().mean()

city_development_index    0.000000
training_hours            0.000000
experience                0.000000
enrollee_id               0.000000
city                      0.000000
gender                    0.237440
relevent_experience       0.000000
enrolled_university       0.020292
education_level           0.024142
major_discipline          0.145961
company_size              0.311823
company_type              0.322524
dtype: float64