### Importing Data Set

In [1]:
import pandas as pd
import numpy as np

url="https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv"
df=pd.read_csv(url)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [2]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

### Data Cleaning by replacing 0 with NaN

In [3]:
columns_to_fix=['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[columns_to_fix]=df[columns_to_fix].replace(0, np.nan)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

### Train Test Split

In [4]:
from sklearn.model_selection import train_test_split

X=df.drop(columns=['Outcome'], axis=1)
Y=df['Outcome']

X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.2, random_state=42)

### Random Forest Regression

In [6]:
from sklearn.ensemble import RandomForestRegressor
 
rf_brain=RandomForestRegressor(n_estimators=10, random_state=42)

### Iterative Imputer

In [7]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer=IterativeImputer(
    estimator=rf_brain,
    random_state=42,
    verbose=2
)

### Fit and Transform

In [8]:
X_train_imputed=imputer.fit_transform(X_train)
X_test_imputed=imputer.transform(X_test)

[IterativeImputer] Completing matrix with shape (614, 8)
[IterativeImputer] Ending imputation round 1/10, elapsed time 0.71
[IterativeImputer] Change: 329.36564349737864, scaled tolerance: 0.846
[IterativeImputer] Ending imputation round 2/10, elapsed time 1.40
[IterativeImputer] Change: 151.2, scaled tolerance: 0.846
[IterativeImputer] Ending imputation round 3/10, elapsed time 2.06
[IterativeImputer] Change: 156.30000000000004, scaled tolerance: 0.846
[IterativeImputer] Ending imputation round 4/10, elapsed time 2.71
[IterativeImputer] Change: 89.79999999999997, scaled tolerance: 0.846
[IterativeImputer] Ending imputation round 5/10, elapsed time 3.30
[IterativeImputer] Change: 88.89999999999999, scaled tolerance: 0.846
[IterativeImputer] Ending imputation round 6/10, elapsed time 3.87
[IterativeImputer] Change: 94.0, scaled tolerance: 0.846
[IterativeImputer] Ending imputation round 7/10, elapsed time 4.51
[IterativeImputer] Change: 105.09999999999998, scaled tolerance: 0.846
[IterativeImputer] Ending imputation round 8/10, elapsed time 5.13
[IterativeImputer] Change: 169.99999999999997, scaled tolerance: 0.846
[IterativeImputer] Ending imputation round 9/10, elapsed time 5.73
[IterativeImputer] Change: 86.40000000000003, scaled tolerance: 0.846
[IterativeImputer] Ending imputation round 10/10, elapsed time 6.29
[IterativeImputer] Change: 74.39999999999999, scaled tolerance: 0.846
[IterativeImputer] Completing matrix with shape (154, 8)
[IterativeImputer] Ending imputation round 1/10, elapsed time 0.01
[IterativeImputer] Ending imputation round 2/10, elapsed time 0.03
[IterativeImputer] Ending imputation round 3/10, elapsed time 0.04
[IterativeImputer] Ending imputation round 4/10, elapsed time 0.05
[IterativeImputer] Ending imputation round 5/10, elapsed time 0.06
[IterativeImputer] Ending imputation round 6/10, elapsed time 0.08
[IterativeImputer] Ending imputation round 7/10, elapsed time 0.09
[IterativeImputer] Ending imputation round 8/10, elapsed time 0.10
[IterativeImputer] Ending imputation round 9/10, elapsed time 0.11
[IterativeImputer] Ending imputation round 10/10, elapsed time 0.13

C:\Users\Digital\anaconda3\Lib\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

### Converting back to Data Frame

In [9]:
X_train_final = pd.DataFrame(X_train_imputed, columns=X.columns)
X_test_final = pd.DataFrame(X_test_imputed, columns=X.columns)

# 8. RESULTS CHECK
print("--- Training Data Missing Values ---")
print(X_train_final.isnull().sum())

print("\n--- Testing Data Missing Values ---")
print(X_test_final.isnull().sum())

display(X_train_final.head())

--- Training Data Missing Values ---
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

--- Testing Data Missing Values ---
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2.0,84.0,66.2,29.0,64.5,31.7,0.304,21.0
1,9.0,112.0,82.0,24.0,135.3,28.2,1.282,50.0
2,1.0,139.0,46.0,19.0,83.0,28.7,0.654,22.0
3,0.0,161.0,50.0,23.1,511.7,21.9,0.254,65.0
4,6.0,134.0,80.0,37.0,370.0,46.2,0.238,46.0